name: scrollable_timeline
version: 1.0.2
description: >-
  A scrollable and draggable timeline that can be driven by an external time stream,
  for example, the current playing time of a YouTube video.
homepage: https://github.com/beyondeye/
repository: https://github.com/beyondeye/flutter_scrollable_timeline
documentation: https://github.com/beyondeye/flutter_scrollable_timeline/blob/master/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
